### PR TITLE
Fix autoloads

### LINKED ISSUE #6: (require 'charmap) doesn't work; (load-file "[etc]/charmap.el") required
I've just installed charmap via the Emacs package manager - charmap version is reported as '20131019.2158'.

Doing a (require 'charmap) doesn't result in any symbols from charmap.el being loaded; so e.g. the 'charmap' interactive command isn't available, the const charmap-char-map isn't defined, and internal functions like 'charmap-print' aren't defined.

However, when I load-file the 'charmap.el' file, everything becomes available.

I'm running a manually-compiled Emacs 24.3 on Debian Wheezy.

### PR DESCRIPTION
**Pull request by piyo**
Fixes #6.

### CODE REVIEW

**Comment by flexibeast** [comment]
Applying this PR, a `(require 'charmap)` makes the `charmap` command available, but trying to run it produces the error `Symbol's function definition is void: substitute`.

**Comment by piyo** [comment]
Huh, I have done (require 'cl) somewhere so I didn't catch this.
Do you think it's okay to replace substitute with cl-substitute and depend on the cl-lib instead of cl? Or use (eval-when-compile (require 'cl))?

**Comment by piyo** [comment]
Okay I removed the use of cl library functions, and I tested it using Emacs 24.5 with the command line emacs -q -Q, as well as verified (eq (featurep 'cl) nil). Please try it out.

**Comment by flexibeast** [comment]
Yep, that works for me. Thanks!

**Pull request merged**
